### ISSUE TITLE
Grpc: error unmarshalling request

### ISSUE THREAD

**Issue by blastin** [codenotary/immudb4j#15]
Java version :  15
Operation System :  20.04.1-Ubuntu
Kernel Linux : 5.8.0-36-generic

## Maven Pom

![image](https://user-images.githubusercontent.com/1932954/104676133-8da6d880-56c5-11eb-90d3-5fc0b83c85ad.png)

## Code

![image](https://user-images.githubusercontent.com/1932954/104676049-66e8a200-56c5-11eb-8751-e46518220d58.png)

## Error

![image](https://user-images.githubusercontent.com/1932954/104675909-26892400-56c5-11eb-89db-28dc2a04bdd2.png)

**Comment by jeroiraz** [comment]
Which immudb version are you running?

**Comment by blastin** [comment]
> Which immudb version are you running?
>  latest. I think is v0.9.0 release
> Thanks for creating the issue!

**Comment by jeroiraz** [comment]
immudb4j was not yet upgraded to support v0.9.0.

You could use v0.8.0: https://github.com/codenotary/immudb/releases/tag/v0.8.0

**Comment by blastin** [comment]
Funcionou. Obrigado pela orientação
