### ISSUE TITLE
Standard library sql interface to query data

### ISSUE THREAD

**Issue by Shashwat32** [codenotary/immudb4j#22]
It would be great for Java SDK to have something like SQLExec API in GO. 

https://docs.immudb.io/master/develop/sqlstdlib.html
https://docs.immudb.io/master/jumpstart.html#sql-operations-with-the-go-sdk

Currently, there is no way for JAVA APIs to support SQL.

**Comment by jeroiraz** [comment]
It's supported in latest release #54
