### ISSUE TITLE
[Feat] JavaSDK 100% grpc api coverage

### ISSUE THREAD

**Issue by tomekkolo** [codenotary/immudb4j#31]
**Description**
JavaSDK must support all GRPC api.

**Action items**
- [ ] All methods can be invoked with a client
- [ ] All methods that support streaming can be used
- [ ] Sessions support
- [ ] Removing tokens

**Comment by byo** [comment]
ExecAll is a bit problematic - java SDK doesn't use raw GRPC structures thus it becomes less priority (SQL etc. are prioritized more). Similar problem with database settings object (e.g. creating / updating databases with settings).
